baseurl = "https://192.168.1.190:1313/"
languageCode = "en-us"
title = "前端小匠"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Wenris"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/wenris/fe-artisan"

	# version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["main.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "cyan"
    	accent  = "deep-orange"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "wenris"
	email   = "wenris@yeah.net"


[[menu.main]]
	name   = "自序"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "索引"
	url    = "contents/"
	weight = 20

[[menu.main]]
	name   = "使用 Ant.D 设计组件"
	url    = "rk-antd/"
	weight = 30

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
